aws:
  region_name: 'us-west-2'
  sqs:
    queue_name: 'job-queue'
database:
  engine: 'postgres'
  user: 'master_user'
  password: 'super_secret_master_password'
  host: 'YOUR DB HOST HERE'
  port: '5432'
  database_name: 'job_server'